version: '3'
services:
  flask:
    # Путь до Dockerfile
    build: ./backend
    image: btls/flask
   # Имя для создаваемого контейнера
    container_name: flask
#    depends_on:
#      - nginx
    # Создание переменных окружения в контейнере
    volumes:
      - ./backend:/backend
    environment:
      - FLASK_APP=/backend/app.py
      # для отладки (при запуске в релиз убрать!)
      - FLASK_ENV=development
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED=True                   
      ##
    # Перезапускаем сервис в случае падения 
    restart: on-failure
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    command: tail -f /dev/null # flask run --host=0.0.0.0 --port=5000
    ports:
      - "8080:5000"
    networks:
      back:
        aliases:
          - flask-app
  btls256:
    build:
      context: ./btls256
    image: btls/btls256
    container_name: btls256
    depends_on:
      - flask
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend\
    volumes:
      - ./btls256:/btls256
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
      - "8446:8446"
    command: tail -f /dev/null
    networks:
      back:
        aliases:
          - btls256
  btls384:
    build:
      context: ./btls384
    image: btls/btls384
    container_name: btls384
    depends_on:
      - flask
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./btls384:/btls384
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
      - "8446:8446"
    command: tail -f /dev/null
    networks:
      back:
        aliases:
          - btls384
  btls512:
    build:
      context: ./btls512
    image: btls/btls512
    container_name: btls512
    depends_on:
      - flask
    # Прокладывам путь для файлов. Все файлы, которые хранятся у вас в 
    # директории ./backend, появятся в директории контейнера /backend
    volumes:
      - ./btls512:/btls512
    ports:
      - "80:80"
      - "443:443"
      - "8443:8443"
      - "8444:8444"
      - "8445:8445"
      - "8446:8446"
    command: tail -f /dev/null
    networks:
      back:
        aliases:
          - btls512

networks:
  back:
    driver: bridge
