name: build

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}
      - name: Build LaTeX
        uses: xu-cheng/latex-action@v4
        with:
          root_file: "spec*/btls.tex"
          working_directory: ./
          work_in_root_file_dir: true
