name: CI to Docker Hub

on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up docker-compose
        run: |
          cd server
          docker-compose build -f ./server/docker-compose.yml --pull
          docker-compose push

#        name: Push to DockerHub
#        

#      - name: Build and push
#        id: docker_build
#        uses: docker/build-push-action@v2
#        with:
#          context: ./
#          file: ./server/Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/btls:latest

#      - name: Image digest
#        run: echo ${{ steps.docker_build.outputs.digest }}